baseURL = 'https://fomenko.dev/'
languageCode = 'en-us'
title = 'Michael Fomenko'
theme = 'gokarna'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1

  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 3

  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 2