baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'gokarna'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1

  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 2

  [[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 3